# ARCHITECTURE
encoder_model_dimension: 512
encoder_num_heads: [4, 4, 4, 4]  # the length of this defines the number of layers
encoder_feed_forward_dimension: 512
encoder_prenet_dimension: 512
encoder_attention_conv_filters: 512
encoder_attention_conv_kernel: 3
encoder_max_position_encoding: 10000
encoder_dense_blocks: 1

# TRAINING
dropout_rate: 0.1
learning_rate_schedule:
  - [0, 1.0e-4]
max_steps: 200_000
debug: False

# LOGGING
validation_frequency: 5_000
prediction_frequency: 5_000
weights_save_frequency: 5_000
train_images_plotting_frequency: 1_000
keep_n_weights: 2
keep_checkpoint_every_n_hours: 12
n_steps_avg_losses: [100, 500, 1_000, 5_000]  # command line display of average loss values for the last n steps
prediction_start_step: 30_000 # step after which to predict durations at validation time