# PATHS: change accordingly
# paths to directory cointaining the wavs
wav_directory: 
  - ['E:/TTSDataset/data_aishell', 'aishell']
  - ['E:/TTSDataset/data_aishell3', 'aishell3']
  - ['E:/TTSDataset/VCTK-Corpus', 'vctk']
  - ['E:/TTSDataset/LibriTTS', 'libritts_360']

data_type:
  aishell: ['mandarin', 'trimnone'] # 'trimcentervad'
  aishell3: ['pinyin', 'trimnone']  # 'trimcentervad'
  vctk: ['english', 'trimnone']
  libritts_360: ['english', 'trimnone']

english_lexion: './data/text/lexion/librispeech-lexicon.txt'
pinyin_lexion: './data/text/lexion/pinyin-lexicon-r.txt'
log_directory: './logs'   # weights and logs are stored here
train_data_directory: 'E:/TTSDataset/Corpus/transformer_tts_data'   # training data is stored here
data_config: './config/data_config.yaml'
asr_config: './config/asr_config.yaml'
tts_config: './config/tts_config.yaml'

data_name: corpus # raw data naming for default data reader (select function from data/metadata_readers.py)